import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import LeftSideBar from '@/components/LeftSideBar';
import RightSideBar from '@/components/RightSideBar';

const poppins = Poppins({ weight: '400', subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RouteLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className=' flex bg-black items-center justify-center text-white w-full'>
          <div className=' flex w-[1240px] h-full relative justify-center'>
            <LeftSideBar />
            {children}
            <RightSideBar />
          </div>
        </div>
      </body>
    </html>
  )
}
